- hosts: all
  remote_user: root
  pre_tasks:
    - apt:
        name: python-pip
        state: latest
        install_recommends: no
    - pip:
        name: "{{ item }}"
      loop:
        - docker-py
        - psycopg2

- name: Include a play for setup postgres DB
  import_playbook: docker_postgres.yml

- name: Include a play for setup nginx
  import_playbook: docker_nginx.yml
