- hosts: all
  remote_user: root
  pre_tasks:
    - apt:
        name: python-pip
        state: latest
        install_recommends: no
    - pip:
        name: "{{ item }}"
      loop:
        - docker-py
        - psycopg2

- name: Include a play after another play
  import_playbook: docker_postgres.yml

- hosts: local
  remote_user: root
  tasks:
    - name: test connection
      ping:
      register: result
    - name: show result
      debug:
        var: result
